# index:
#    path: /
#    controller: App\Controller\DefaultController::index
controllers:
    resource: ../src/Controller/
    type: annotation

kernel:
    resource: ../src/Kernel.php
    type: annotation
    
api_check:
    path: /api/login_check
