name: "PhpCs"
on:
  push:
    branches:
      - dev
      - master
  pull_request:
    types: [opened, synchronize, reopened]
jobs:
  phpcs:
    name: PHPCS
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
      - name: PHPCS check
        uses: chekalsky/phpcs-action@v1
        with:
          enable_warnings: true
